[project]
name = "breast-density-classification"
version = "0.1.0"
description = "Breast density classification using CNNs"
authors = [{name = "Matheus Loiola Pinto Curado Silva", email = "matheusloiolapinto@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "pyyaml>=6.0.2",
    "torch>=2.5.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.7.1",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
