meta:
    seed: 42

data:
    datasets_path: '/home/loioladev/git/breast-density-classification/data'       # path to structured folder of datasets
    datasets: ['inbreast']  # available datasets ['inbreast']
    sampler: ''   # choose between ['weightened', 'random', 'sequential']
    batch_size: 8
    workers: 4

logging:
    folder: './logs'
    level: 'INFO'
