meta:
    seed: 42
    load_checkpoint: True
    model_name: 'resnet50'
    training_folder: './runs'

augmentation:
    height: 336
    width: 224

data:
    datasets_path: '/home/loioladev/git/breast-density-classification/data'       
    datasets: ['inbreast']
    sampler: 'weightened'
    batch_size: 8
    workers: 4

logging:
    level: 'INFO'
